import { LitElement, html } from "lit-element";

// CLASE DE ORIENTADA A OBJETOS QUE HEREDA CARACTERISTICAS DE LITELEMENT
class HolaMundo extends LitElement {
  // METODO DONDE SE DEFINEN LAS PROPIEDADES QUE TENDRA EL WEB COMPONENT
  // CUANDO EL VALOR DE UNA PROPIEDAD CAMBIA/ACTUALIZA EL TEMPLATE REFLEJA ESE CAMBIO A TRAVES DE LIT-HTML
  static get properties() {
    return {
      quien: { type: String }
    };
  }

  // RENDER ES EL METODO PRINCIPAL QUE PERMITE RENDERIZAR EL COMPONENTE, LO QUE REGRESA ES UN TEMPLATE HTML DEFINIDO POR EL DESARROLLADOR
  // EXISTEN MUCHOS MAS METODOS ESTABLECIDOS Y LOS DEFINIDOS POR EL DESARROLLADOR
  render() {
    // HTML ES LA DEPENDENCIA QUE SE ESTA IMPORTANDO AL INICIO
    // HTML ES UN TEMPLATE STRING, CARACTERISTICA QUE SE INTRODUJO EN ES6
    return html`

      <!-- PARA PODER MOSTRAR EL VALOR DE LA PROPIEDAD DEFINIDA SE HACE UNA INTERPOLACION DE LA VARIABLE Y SE USA EL OBJETO "THIS" PARA HACER REFERENCIA AL WEB COMPONENT -->
      <p>Hola mundo desde <b> ${this.quien} </b></p>
    `;
  }
}

// DEFINE PERTENECE AL ESTANDAR DE LOS WEB COMPONENTS, NO ES PROPIO DE LITELEMENT
customElements.define('hola-mundo', HolaMundo);
