/*
  BLOQUE TRY: SE ENCUENTRA EL CÓDIGO QUE SE EVALUARÁ, SI DENTRO DE ESTA SECCIÓN
  SE ENCUENTRA O SURGE ALGÚN ERROR ENTONCES LA PARTE DEL CATCH HARÁ LO QUE DEFINAMOS.

  BLOQUE CATCH: CAPTURA CUALQUIER ERROR SURGIDO O LANZADO EN EL TRY.

  BLOQUE FINALLY: SE EJECUTARÁ SIEMPRE AL FINAL DE UN BLOQUE, AUNQUE HAYA SURGIDO ALGÚN ERROR O NO.
*/

try {
  console.log("ESTOY EN EL TRY");
} catch(error) {
  console.log("ESTOY EN EL CATCH");
} finally {
  console.log("ESTOY EN EL FINALLY");
};
